name: unitTest

on:
  push:
    branches:
      - dev-*

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"

      - name: check node and npm version
        run: |
          node --version
          npm --version

      - name: test run
        run: |
          npm ci
          npm run test
